
services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .db_info
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
  backend:
    build: ./BOBcat_website/
    restart: always
    # Use the Django development server for auto-reloading
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      # Maps your local code to the container's working directory.
      # IMPORTANT: Change '/app' to whatever WORKDIR is set in your Dockerfile!
      - ./BOBcat_website/:/app
    env_file:
      - .db_info
    depends_on:
      - db

volumes:
  postgres_data: