"""
Django settings for BOBcat_website project.

Generated by 'django-admin startproject' using Django 4.0.4.
Refactored by Dominic and Google Gemini 3.1

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '0') != '0'

_ALLOWED = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').strip()
ALLOWED_HOSTS = [h.strip() for h in _ALLOWED.split(',') if h.strip()]


# Application definition

# This is a public, read-only catalog with no user accounts and no admin.
# The auth/sessions/messages/contenttypes contrib apps are intentionally
# omitted -- nothing in the project uses request.user, sessions, flash
# messages, or content types, so they'd only add unused tables and surface.
# CSRF still works without sessions (it defaults to cookie-based tokens).
INSTALLED_APPS = [
    "mainpage",
    "BOBcat_utils",
    # "search",
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BOBcat_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "mainpage" / "templates",
            BASE_DIR / "BOBcat_website" / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'BOBcat_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'bobcat'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    },
    # Limited-privilege role used to execute user-submitted SQL queries.
    # Run `python manage.py setup_readonly_db_user` once to create the role,
    # then set READONLY_DB_USER / READONLY_DB_PASSWORD in your .db_info file.
    'readonly': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'bobcat'),
        'USER': os.environ.get('READONLY_DB_USER', 'bobcat_readonly'),
        'PASSWORD': os.environ.get('READONLY_DB_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    },
}


# Password validation is intentionally omitted -- django.contrib.auth is not
# installed (no user accounts), so there are no passwords for Django to manage.


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    # Project-level static assets (e.g. base.css).
    # App-level static files (mainpage/static/) are discovered automatically
    # by AppDirectoriesFinder because 'mainpage' is in INSTALLED_APPS.
    BASE_DIR / "BOBcat_website" / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
# These all assume something in front of Django actually terminates HTTPS
# and forwards X-Forwarded-Proto. Tied to DJANGO_BEHIND_TLS rather than just
# `not DEBUG`: the docker-compose nginx has no TLS listener, so with these on
# but no TLS anywhere, SECURE_SSL_REDIRECT sends every request to an https
# port nothing is listening on, and SESSION/CSRF_COOKIE_SECURE stop the
# browser from ever sending those cookies back over plain HTTP -- breaking
# logins and CSRF-protected forms site-wide, not just redirecting. Set
# DJANGO_BEHIND_TLS=1 once a real TLS terminator (nginx cert or an upstream
# load balancer) is actually in place.
if not DEBUG and os.environ.get('DJANGO_BEHIND_TLS', '0') != '0':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Sensitivities / PTA sky assets (optional)
BOBCAT_HLIM_TXT = Path(
	os.environ.get('BOBCAT_HLIM_TXT', str(BASE_DIR / 'data' / 'hlim.txt')),
)
BOBCAT_PTA_HP_PATH = Path(
	os.environ.get('BOBCAT_PTA_HP_PATH', str(BASE_DIR.parent / 'data' / 'PTA.hpx')),
)
