# Generated by Django 6.0.5 on 2026-05-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('paper_link', models.URLField()),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ned_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_param_link', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('waveband', models.CharField(blank=True, max_length=25, null=True)),
                ('model_param_link', models.ForeignKey(db_column='model_param_link', on_delete=django.db.models.deletion.CASCADE, to='mainpage.papers')),
            ],
        ),
        migrations.CreateModel(
            name='BinaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.CharField(help_text='Internal identifier linking this entry to its source spreadsheet', max_length=100)),
                ('paper', models.CharField(blank=True, help_text='Citation key or bibcode for the paper this model is drawn from', max_length=200, null=True)),
                ('eccentricity', models.FloatField(blank=True, help_text='Orbital eccentricity (0 = circular, 0–1 = bound elliptical orbit)', null=True)),
                ('m1', models.FloatField(blank=True, help_text='Primary black hole mass in solar masses (M☉)', null=True)),
                ('m2', models.FloatField(blank=True, help_text='Secondary black hole mass in solar masses (M☉)', null=True)),
                ('mtot', models.FloatField(blank=True, help_text='Total system mass m1 + m2 in solar masses (M☉)', null=True)),
                ('mc', models.FloatField(blank=True, help_text='Chirp mass — the mass combination that governs GW inspiral rate (M☉)', null=True)),
                ('mu', models.FloatField(blank=True, help_text='Reduced mass μ = m1·m2 / (m1+m2) in solar masses (M☉)', null=True)),
                ('q', models.FloatField(blank=True, help_text='Mass ratio q = m2/m1, where q ≤ 1 by convention', null=True)),
                ('inclination', models.FloatField(blank=True, help_text='Orbital inclination relative to the line of sight, in degrees', null=True)),
                ('semimajor_axis', models.FloatField(blank=True, help_text='Semimajor axis of the binary orbit in parsecs', null=True)),
                ('seperation', models.FloatField(blank=True, help_text='Physical separation between the two black holes in parsecs', null=True)),
                ('period_epoch', models.FloatField(blank=True, help_text='Reference epoch (MJD) at which the orbital period is defined', null=True)),
                ('orb_freq', models.FloatField(blank=True, help_text='Orbital frequency in Hz', null=True)),
                ('orb_period', models.FloatField(blank=True, help_text='Orbital period in years', null=True)),
                ('summary', models.TextField(blank=True, help_text='Brief description of the model methodology and assumptions', null=True)),
                ('caveats', models.TextField(blank=True, help_text='Known limitations, degeneracies, or assumptions to be aware of', max_length=500, null=True)),
                ('ext_proj', models.TextField(blank=True, help_text='Associated external project or observing campaign', max_length=100, null=True)),
                ('gw_strain', models.FloatField(blank=True, help_text='Gravitational wave strain amplitude h at Earth', null=True)),
                ('gw_freq', models.FloatField(blank=True, help_text='Gravitational wave frequency in Hz (typically 2× the orbital frequency)', null=True)),
                ('gw_strain_err', models.FloatField(blank=True, help_text='1σ uncertainty on the gravitational wave strain', null=True)),
                ('gw_freq_err', models.FloatField(blank=True, help_text='1σ uncertainty on the gravitational wave frequency in Hz', null=True)),
                ('model_param_link', models.OneToOneField(db_column='model_param_link', on_delete=django.db.models.deletion.CASCADE, to='mainpage.papers')),
            ],
        ),
    ]
