# Generated by Django 6.0.6 on 2026-06-23 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bib',
            fields=[
                ('bib_id', models.CharField(max_length=29, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('citations', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bib',
            },
        ),
        migrations.CreateModel(
            name='ObsPeriod',
            fields=[
                ('obs_period_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('waveband', models.CharField(blank=True, choices=[('radio', 'Radio'), ('infrared', 'Infrared'), ('optical', 'Optical'), ('UV', 'UV'), ('x-ray', 'X-ray'), ('gamma-ray', 'Gamma-ray')], max_length=10, null=True)),
                ('value', models.FloatField(help_text='Measured period')),
                ('epoch', models.FloatField(help_text='Reference epoch in MJD')),
            ],
            options={
                'db_table': 'obs_period',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('jra', models.FloatField(help_text='Right ascension in decimal degrees (J2000)')),
                ('jdec', models.FloatField(help_text='Declination in decimal degrees (J2000)')),
                ('redshift', models.FloatField(blank=True, help_text='Spectroscopic redshift', null=True)),
                ('lum_dist', models.FloatField(blank=True, help_text='Luminosity distance in Mpc', null=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidate',
                'indexes': [models.Index(fields=['name'], name='candidate_name_5539eb_idx'), models.Index(fields=['jra', 'jdec'], name='candidate_jra_12f73d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BinaryModel',
            fields=[
                ('binary_model_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('sheet_id', models.TextField(blank=True, null=True)),
                ('eccentricity', models.FloatField(blank=True, help_text='Orbital eccentricity (0 = circular)', null=True)),
                ('m1', models.FloatField(blank=True, help_text='Larger BH mass in M☉', null=True)),
                ('m2', models.FloatField(blank=True, help_text='Smaller BH mass in M☉', null=True)),
                ('mtot', models.FloatField(blank=True, help_text='Total mass m1+m2 in M☉', null=True)),
                ('mc', models.FloatField(blank=True, help_text='Chirp mass in M☉', null=True)),
                ('mu', models.FloatField(blank=True, help_text='Reduced mass in M☉', null=True)),
                ('q', models.FloatField(blank=True, help_text='Mass ratio m2/m1 ≤ 1', null=True)),
                ('inclination', models.FloatField(blank=True, help_text='Orbital inclination in degrees', null=True)),
                ('semimajor_axis', models.FloatField(blank=True, help_text='Semimajor axis in parsecs', null=True)),
                ('separation', models.FloatField(blank=True, help_text='Projected separation in parsecs', null=True)),
                ('rm_orb_period', models.FloatField(blank=True, db_column='RM_orb_period', help_text='Earth-frame orbital period in years', null=True)),
                ('rm_orb_period_epoch', models.FloatField(blank=True, db_column='RM_orb_period_epoch', help_text='Reference epoch (MJD) for the orbital period', null=True)),
                ('gw_strain', models.FloatField(blank=True, help_text='GW strain amplitude h at Earth (circular orbit)', null=True)),
                ('gw_inspiral_timescale', models.FloatField(blank=True, help_text='Time to coalescence in seconds (GR, circular orbit)', null=True)),
                ('summary', models.CharField(blank=True, help_text='Brief description of the binary model', max_length=750, null=True)),
                ('caveats', models.CharField(blank=True, help_text='Known limitations or assumptions', max_length=750, null=True)),
                ('ext_proj', models.CharField(blank=True, help_text='Related external project or survey', max_length=750, null=True)),
                ('bib', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.bib')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.candidate')),
            ],
            options={
                'db_table': 'binary_model',
            },
        ),
        migrations.CreateModel(
            name='EvidenceSubcategory',
            fields=[
                ('evidence_subcategory_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('spectral_line_variability', 'Spectral Line Variability'), ('spectral_line_snapshot', 'Spectral Line Snapshot'), ('continuum_variability', 'Continuum Variability'), ('spatially_resolved_offset_or_dual_AGN', 'Spatially Resolved Offset / Dual AGN'), ('pc_jet_morphology', 'pc-scale Jet Morphology'), ('kpc_jet_morphology', 'kpc-scale Jet Morphology'), ('host_galaxy', 'Host Galaxy'), ('gravitational_wave', 'Gravitational Wave'), ('SED_feature', 'SED Feature')], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'evidence_subcategory',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ModelEvidence',
            fields=[
                ('model_evidence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('binary_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.binarymodel')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.evidencesubcategory')),
            ],
            options={
                'db_table': 'model_evidence',
            },
        ),
        migrations.CreateModel(
            name='ModelEvidenceWaveband',
            fields=[
                ('model_evidence_waveband_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('waveband', models.CharField(choices=[('radio', 'Radio'), ('infrared', 'Infrared'), ('optical', 'Optical'), ('UV', 'UV'), ('x-ray', 'X-ray'), ('gamma-ray', 'Gamma-ray')], max_length=10)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.modelevidence')),
            ],
            options={
                'db_table': 'model_evidence_waveband',
            },
        ),
        migrations.CreateModel(
            name='ObsPeriodError',
            fields=[
                ('obs_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainpage.obsperiod')),
                ('error_type', models.CharField(blank=True, choices=[('Assumed', 'Assumed'), ('Upper limit', 'Upper limit'), ('Lower limit', 'Lower limit'), ('Gaussian', 'Gaussian'), ('Two-sided', 'Two-sided'), ('Representative', 'Representative')], max_length=20, null=True)),
                ('error_upper', models.FloatField(blank=True, null=True)),
                ('error_lower', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'obs_period_error',
            },
        ),
        migrations.AddField(
            model_name='obsperiod',
            name='binary_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.binarymodel'),
        ),
        migrations.CreateModel(
            name='BinaryModelError',
            fields=[
                ('binary_model_error_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(help_text="Parameter name, e.g. 'mtot', 'separation'", max_length=25)),
                ('error_type', models.CharField(blank=True, choices=[('Assumed', 'Assumed'), ('Upper limit', 'Upper limit'), ('Lower limit', 'Lower limit'), ('Gaussian', 'Gaussian'), ('Two-sided', 'Two-sided'), ('Representative', 'Representative')], max_length=20, null=True)),
                ('error_upper', models.FloatField(blank=True, null=True)),
                ('error_lower', models.FloatField(blank=True, null=True)),
                ('binary_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.binarymodel')),
            ],
            options={
                'db_table': 'binary_model_error',
                'unique_together': {('binary_model', 'property_name')},
            },
        ),
        migrations.AddIndex(
            model_name='binarymodel',
            index=models.Index(fields=['candidate'], name='binary_mode_candida_53f656_idx'),
        ),
        migrations.AddIndex(
            model_name='binarymodel',
            index=models.Index(fields=['bib'], name='binary_mode_bib_id_abf2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='binarymodel',
            index=models.Index(fields=['mtot'], name='binary_mode_mtot_237fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='modelevidence',
            index=models.Index(fields=['binary_model'], name='model_evide_binary__a4d158_idx'),
        ),
        migrations.AddIndex(
            model_name='modelevidence',
            index=models.Index(fields=['subcategory'], name='model_evide_subcate_ee30b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelevidencewaveband',
            unique_together={('evidence', 'waveband')},
        ),
        migrations.AddIndex(
            model_name='obsperiod',
            index=models.Index(fields=['binary_model'], name='obs_period_binary__a7d5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='obsperiod',
            index=models.Index(fields=['value'], name='obs_period_value_3c89f3_idx'),
        ),
    ]
