# Generated by Django 6.0.5 on 2026-05-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarymodel',
            name='caveats',
            field=models.TextField(blank=True, help_text='Known limitations, degeneracies, or assumptions to be aware of', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='eccentricity',
            field=models.FloatField(blank=True, help_text='Orbital eccentricity (0 = circular, 0–1 = bound elliptical orbit)', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='ext_proj',
            field=models.TextField(blank=True, help_text='Associated external project or observing campaign', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='gw_freq',
            field=models.FloatField(blank=True, help_text='Gravitational wave frequency in Hz (typically 2× the orbital frequency)', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='gw_freq_err',
            field=models.FloatField(blank=True, help_text='1σ uncertainty on the gravitational wave frequency in Hz', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='gw_strain',
            field=models.FloatField(blank=True, help_text='Gravitational wave strain amplitude h at Earth', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='gw_strain_err',
            field=models.FloatField(blank=True, help_text='1σ uncertainty on the gravitational wave strain', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='inclination',
            field=models.FloatField(blank=True, help_text='Orbital inclination relative to the line of sight, in degrees', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='m1',
            field=models.FloatField(blank=True, help_text='Primary black hole mass in solar masses (M☉)', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='m2',
            field=models.FloatField(blank=True, help_text='Secondary black hole mass in solar masses (M☉)', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='mc',
            field=models.FloatField(blank=True, help_text='Chirp mass — the mass combination that governs GW inspiral rate (M☉)', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='mtot',
            field=models.FloatField(blank=True, help_text='Total system mass m1 + m2 in solar masses (M☉)', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='mu',
            field=models.FloatField(blank=True, help_text='Reduced mass μ = m1·m2 / (m1+m2) in solar masses (M☉)', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='orb_freq',
            field=models.FloatField(blank=True, help_text='Orbital frequency in Hz', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='orb_period',
            field=models.FloatField(blank=True, help_text='Orbital period in years', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='paper',
            field=models.CharField(blank=True, help_text='Citation key or bibcode for the paper this model is drawn from', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='period_epoch',
            field=models.FloatField(blank=True, help_text='Reference epoch (MJD) at which the orbital period is defined', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='q',
            field=models.FloatField(blank=True, help_text='Mass ratio q = m2/m1, where q ≤ 1 by convention', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='semimajor_axis',
            field=models.FloatField(blank=True, help_text='Semimajor axis of the binary orbit in parsecs', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='seperation',
            field=models.FloatField(blank=True, help_text='Physical separation between the two black holes in parsecs', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='sheet_id',
            field=models.CharField(help_text='Internal identifier linking this entry to its source spreadsheet', max_length=100),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='summary',
            field=models.TextField(blank=True, help_text='Brief description of the model methodology and assumptions', null=True),
        ),
    ]
