# Generated by Django 4.0.4 on 2024-05-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='dec',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='ra',
            field=models.CharField(max_length=20),
        ),
    ]
