# Generated by Django 6.0.6 on 2026-06-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencesubcategory',
            name='category',
            field=models.CharField(choices=[('spectral_line_variability', 'Spectral Line Variability'), ('spectral_line_snapshot', 'Spectral Line Snapshot'), ('continuum_variability', 'Continuum Variability'), ('spatially_resolved_offset_or_dual_AGN', 'Spatially Resolved Offset / Dual AGN'), ('pc_jet_morphology', 'pc-scale Jet Morphology'), ('kpc_jet_morphology', 'kpc-scale Jet Morphology'), ('host_galaxy', 'Host Galaxy'), ('gravitational_wave', 'Gravitational Wave'), ('SED_feature', 'SED Feature')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bib',
            name='bib_id',
            field=models.CharField(max_length=29, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.candidate'),
        ),
        migrations.AlterField(
            model_name='binarymodelerror',
            name='binary_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.binarymodel'),
        ),
        migrations.AlterField(
            model_name='modelevidence',
            name='binary_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.binarymodel'),
        ),
        migrations.AlterField(
            model_name='modelevidencewaveband',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.modelevidence'),
        ),
        migrations.AlterField(
            model_name='obsperiod',
            name='binary_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.binarymodel'),
        ),
        migrations.AlterField(
            model_name='obsperioderror',
            name='obs_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainpage.obsperiod'),
        ),
        migrations.DeleteModel(
            name='EvidenceCategory',
        ),
    ]
