# Generated by Django 6.0.6 on 2026-07-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_rm_orb_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarymodel',
            name='gw_strain',
            field=models.FloatField(blank=True, help_text='log of GW strain amplitude h at Earth (circular orbit)', null=True),
        ),
    ]
