# Generated by Django 6.0.6 on 2026-06-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_evidencesubcategory_category_alter_bib_bib_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencesubcategory',
            name='category',
            field=models.CharField(choices=[('spectral_line_variability', 'Spectral Line Variability'), ('spectral_line_snapshot', 'Spectral Line Snapshot'), ('continuum_variability', 'Continuum Variability'), ('spatially_resolved_offset_or_dual_AGN', 'Spatially Resolved Offset / Dual AGN'), ('pc_jet_morphology', 'pc-scale Jet Morphology'), ('kpc_jet_morphology', 'kpc-scale Jet Morphology'), ('host_galaxy', 'Host Galaxy'), ('gravitational_wave', 'Gravitational Wave'), ('SED_feature', 'SED Feature')], max_length=100),
        ),
        migrations.AlterField(
            model_name='evidencesubcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
