# Generated by Django 4.0.4 on 2024-06-28 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_source_ads_bibcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='id',
        ),
        migrations.AlterField(
            model_name='source',
            name='NED_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='redshift',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.CreateModel(
            name='binary_model',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paper_link', models.URLField(max_length=300)),
                ('eccentricity', models.DecimalField(decimal_places=5, max_digits=8)),
                ('m1', models.BigIntegerField()),
                ('m2', models.BigIntegerField()),
                ('total_mass', models.BigIntegerField()),
                ('chirp_mass', models.BigIntegerField()),
                ('reduced_mass', models.BigIntegerField()),
                ('q', models.DecimalField(decimal_places=4, max_digits=8)),
                ('evid_type_1', models.CharField(max_length=50)),
                ('evid_type_1_note', models.CharField(max_length=50)),
                ('evid_type_1_waveband', models.CharField(max_length=50)),
                ('evid_type_2', models.CharField(max_length=50)),
                ('evid_type_2_note', models.CharField(max_length=50)),
                ('evid_type_2_waveband', models.CharField(max_length=50)),
                ('evid_type_3', models.CharField(max_length=50)),
                ('evid_type_3_note', models.CharField(max_length=50)),
                ('evid_type_3_waveband', models.CharField(max_length=50)),
                ('evid_type_4', models.CharField(max_length=50)),
                ('evid_type_4_note', models.CharField(max_length=50)),
                ('evid_type_4_waveband', models.CharField(max_length=50)),
                ('inclination', models.DecimalField(decimal_places=5, max_digits=8)),
                ('semi_major_axis', models.DecimalField(decimal_places=5, max_digits=8)),
                ('separation', models.DecimalField(decimal_places=5, max_digits=8)),
                ('period_epoch', models.IntegerField()),
                ('orb_freq', models.DecimalField(decimal_places=5, max_digits=10)),
                ('orb_period', models.DecimalField(decimal_places=5, max_digits=10)),
                ('summary', models.TextField()),
                ('caveats', models.TextField()),
                ('ext_projects', models.TextField()),
                ('source_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.source')),
            ],
        ),
    ]
