# Generated by Django 6.0.6 on 2026-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_evidencesubcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarymodel',
            name='caveats',
            field=models.CharField(blank=True, help_text='Known limitations or assumptions', max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='eccentricity',
            field=models.FloatField(blank=True, help_text='Orbital eccentricity (0 = circular)', null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='ext_proj',
            field=models.CharField(blank=True, help_text='Related external project or survey', max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='summary',
            field=models.CharField(blank=True, help_text='Brief description of the binary model', max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jdec',
            field=models.FloatField(help_text='Declination in decimal degrees (J2000)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jra',
            field=models.FloatField(help_text='Right ascension in decimal degrees (J2000)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lum_dist',
            field=models.FloatField(blank=True, help_text='Luminosity distance in Mpc', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='redshift',
            field=models.FloatField(blank=True, help_text='Spectroscopic redshift', null=True),
        ),
    ]
