# Generated by Django 4.0.4 on 2024-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_source_id_alter_source_ned_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary_model',
            name='source_name',
            field=models.CharField(max_length=20),
        ),
    ]
