# Generated by Django 4.0.4 on 2024-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_binary_model_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary_model',
            name='m2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
