# Generated by Django 4.0.4 on 2024-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_binary_model_m2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary_model',
            name='chirp_mass',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='eccentricity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='inclination',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='m1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='orb_freq',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='orb_period',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='paper_link',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='period_epoch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='q',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='reduced_mass',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='semi_major_axis',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='separation',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='source_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='binary_model',
            name='total_mass',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
