# Generated by Django 4.0.4 on 2024-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_binary_model_caveats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binary_model',
            name='gw_freq',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='binary_model',
            name='gw_strain',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
