# Generated by Django 4.0.4 on 2024-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_binary_model_gw_freq_binary_model_gw_strain'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='luminosity_distance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
