# Generated by Django 4.0.4 on 2024-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_source_luminosity_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='luminosity_distance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
