# Generated by Django 4.0.4 on 2024-07-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_alter_source_luminosity_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='luminosity_distance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
    ]
