# Generated by Django 4.0.4 on 2025-04-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_rename_source_name_binary_model_candidate_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='NED_name',
            new_name='ned_name',
        ),
    ]
