# Generated by Django 4.0.4 on 2025-04-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_rename_ned_name_source_ned_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binary_model',
            old_name='id',
            new_name='binary_model_id',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='ned_name',
            new_name='NED_name',
        ),
    ]
