# Generated by Django 4.0.4 on 2025-04-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_rename_ned_name_source_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='source',
            new_name='candidate',
        ),
    ]
