# Generated by Django 4.0.4 on 2025-04-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_rename_source_candidate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='candidate',
        ),
    ]
