# Generated by Django 4.0.4 on 2025-04-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_alter_candidate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BinaryModel',
            fields=[
                ('binary_model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('paper', models.CharField(blank=True, max_length=200, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('m1', models.FloatField(blank=True, null=True)),
                ('m2', models.FloatField(blank=True, null=True)),
                ('mtot', models.FloatField(blank=True, null=True)),
                ('mc', models.FloatField(blank=True, null=True)),
                ('mu', models.FloatField(blank=True, null=True)),
                ('q', models.FloatField(blank=True, null=True)),
                ('evid1_type', models.CharField(blank=True, max_length=100, null=True)),
                ('evid1_note', models.CharField(blank=True, max_length=500, null=True)),
                ('evid1_wavelength', models.CharField(blank=True, max_length=25, null=True)),
                ('evid2_type', models.CharField(blank=True, max_length=100, null=True)),
                ('evid2_note', models.CharField(blank=True, max_length=500, null=True)),
                ('evid2_wavelength', models.CharField(blank=True, max_length=25, null=True)),
                ('evid3_type', models.CharField(blank=True, max_length=100, null=True)),
                ('evid3_note', models.CharField(blank=True, max_length=500, null=True)),
                ('evid3_wavelength', models.CharField(blank=True, max_length=25, null=True)),
                ('evid4_type', models.CharField(blank=True, max_length=100, null=True)),
                ('evid4_note', models.CharField(blank=True, max_length=500, null=True)),
                ('evid4_wavelength', models.CharField(blank=True, max_length=25, null=True)),
                ('inclination', models.FloatField(blank=True, null=True)),
                ('semimajor_axis', models.FloatField(blank=True, null=True)),
                ('seperation', models.FloatField(blank=True, null=True)),
                ('period_epoch', models.FloatField(blank=True, null=True)),
                ('orb_freq', models.FloatField(blank=True, null=True)),
                ('orb_period', models.FloatField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('caveats', models.CharField(blank=True, max_length=100, null=True)),
                ('ext_proj', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'binary_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainpageBinaryModel',
            fields=[
                ('binary_model_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paper', models.CharField(blank=True, max_length=300, null=True)),
                ('eccentricity', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('m1', models.BigIntegerField(blank=True, null=True)),
                ('m2', models.BigIntegerField(blank=True, null=True)),
                ('mu', models.BigIntegerField(blank=True, null=True)),
                ('mc', models.BigIntegerField(blank=True, null=True)),
                ('mtot', models.BigIntegerField(blank=True, null=True)),
                ('q', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('evid1_note', models.CharField(blank=True, max_length=50, null=True)),
                ('evid1_type', models.CharField(blank=True, max_length=50, null=True)),
                ('evid1_wavelength', models.CharField(blank=True, max_length=50, null=True)),
                ('evid2_note', models.CharField(blank=True, max_length=50, null=True)),
                ('evid2_type', models.CharField(blank=True, max_length=50, null=True)),
                ('evid2_wavelength', models.CharField(blank=True, max_length=50, null=True)),
                ('evid3_note', models.CharField(blank=True, max_length=50, null=True)),
                ('evid3_type', models.CharField(blank=True, max_length=50, null=True)),
                ('evid3_wavelength', models.CharField(blank=True, max_length=50, null=True)),
                ('evid4_note', models.CharField(blank=True, max_length=50, null=True)),
                ('evid4_type', models.CharField(blank=True, max_length=50, null=True)),
                ('evid4_wavelength', models.CharField(blank=True, max_length=50, null=True)),
                ('inclination', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('semimajor_axis', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('separation', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('period_epoch', models.IntegerField(blank=True, null=True)),
                ('orb_freq', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('orb_period', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('caveats', models.TextField(blank=True, null=True)),
                ('ext_proj', models.TextField(blank=True, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mainpage_binary_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainpageCandidate',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('obs_type_done', models.CharField(max_length=20)),
                ('ra_deg', models.DecimalField(decimal_places=5, max_digits=8)),
                ('dec_deg', models.DecimalField(decimal_places=5, max_digits=8)),
                ('redshift', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'db_table': 'mainpage_candidate',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='binary_model',
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'managed': False},
        ),
    ]
