# Generated by Django 4.0.4 on 2025-04-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_rename_id_binary_model_binary_model_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='NED_name',
            new_name='name',
        ),
    ]
