# Generated by Django 6.0.5 on 2026-05-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryModel',
            fields=[
                ('sheet_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('paper', models.CharField(blank=True, max_length=200, null=True)),
                ('eccentricity', models.FloatField(blank=True, null=True)),
                ('m1', models.FloatField(blank=True, null=True)),
                ('m2', models.FloatField(blank=True, null=True)),
                ('mtot', models.FloatField(blank=True, null=True)),
                ('mc', models.FloatField(blank=True, null=True)),
                ('mu', models.FloatField(blank=True, null=True)),
                ('q', models.FloatField(blank=True, null=True)),
                ('inclination', models.FloatField(blank=True, null=True)),
                ('semimajor_axis', models.FloatField(blank=True, null=True)),
                ('seperation', models.FloatField(blank=True, null=True)),
                ('period_epoch', models.FloatField(blank=True, null=True)),
                ('orb_freq', models.FloatField(blank=True, null=True)),
                ('orb_period', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('caveats', models.TextField(blank=True, max_length=500, null=True)),
                ('ext_proj', models.TextField(blank=True, max_length=100, null=True)),
                ('gw_strain', models.FloatField(blank=True, null=True)),
                ('gw_freq', models.FloatField(blank=True, null=True)),
                ('gw_strain_err', models.FloatField(blank=True, null=True)),
                ('gw_freq_err', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_link', models.URLField(unique=True)),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ned_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_param_link', models.URLField()),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('wavelength', models.CharField(blank=True, max_length=25, null=True)),
                ('binary_model_id', models.ForeignKey(db_column='sheet_id', on_delete=django.db.models.deletion.CASCADE, to='sourcepage.binarymodel')),
            ],
        ),
        migrations.AddField(
            model_name='binarymodel',
            name='candidate_name',
            field=models.ForeignKey(blank=True, db_column='candidate_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sourcepage.papers'),
        ),
    ]
