# Generated by Django 6.0.5 on 2026-05-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binarymodel',
            name='candidate_name',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='binary_model_id',
        ),
        migrations.AddField(
            model_name='binarymodel',
            name='model_param_link',
            field=models.ForeignKey(db_column='model_param_link', default='plink', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sourcepage.papers', to_field='model_param_link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='binarymodel',
            name='sheet_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='papers',
            name='model_param_link',
            field=models.URLField(unique=True),
        ),
    ]
